### ISSUE TITLE
Enhacement proposal for enabling proxying of controls over websockets

### ISSUE THREAD

**Issue by Feijk** [donmccurdy/aframe-gamepad-controls#3]
I recently did a test to stream controls from a host machine to a client over websockets. The latencies I faced on a local network where acceptable and I was able to implement the WASD -controls over websockets using Socket.io running on a simple Node.js server.

My goal is to achieve a platform independent solution for connecting gamepads to webvr/A-Frame -based content. Any interest in an implementation towards this approach? Suggestions?

**Comment by donmccurdy** [comment]
Hi @Feijk - Yes, I've been hoping to do exactly that. Nice to hear others are interested! 😊 

I managed to get this working experimentally using PeerJS (with WebRTC, not websockets); if you look at `gamepad-controls.js::getGamepad()`, you'll see that it checks for a `proxy-controls` component and tries to fetch gamepad state from that if it can. If not, it uses the native Gamepad implementation.

My (currently broken) implementation of `proxy-controls`, which receives input events from a host machine, is here: https://github.com/donmccurdy/aframe-proxy-controls

I'm hoping to move away from PeerJS and use either Socket.io or [socketpeer](https://github.com/cvan/socketpeer) in order to use websockets as a fallback for WebRTC.

I'd definitely welcome help or feedback in trying to make this work. Thanks!

**Comment by Feijk** [comment]
Awesome! Just what I was hoping for. Didn't notice the `proxy-controls` component in the code at first glance, but seems like a good solution :+1: . I'll have a look at your aframe-proxy-controls component and see if I can make it work via socketkeeper and make a PR once I have something working!

Socketpeer appears to have all the basics in place so I think it's a good starting point, will test and report back!

**Comment by donmccurdy** [comment]
Cool, good luck! `proxy-controls` is just the client component for the viewing device, but I also started on a WebRTC signaling server and a client for the host machine: https://github.com/donmccurdy/proxy-controls-server

Right now that's using Socket.io, but socketpeer also looks really good. I'm open to using either at this point, so let me know how things go for you. Socket.io seems a bit bulky, but it's better documented.

**Comment by Feijk** [comment]
Thanks! I'll have a look at your proxy-controls-server too and see where I end up with all these together. If you wanna have a look at the [tech demo](https://storage.googleapis.com/nvf-misc/feijk-vrdemo.zip) I was talking about in my first post, just dl the package and run `npm install` && `node index.js`.

There's a forked version of a-frame in there where I have replaced some of the native WASD -component methods to support streaming commands. To enable WASD on the host just click both buttons on the HUD when playing (first 'CONTROLS' then 'A SCREEN'). It's a bit messy, but does the trick. I've also included a little world geometry I did in Blender to have something to play around with (no textures or real shading yet though).

**Comment by donmccurdy** [comment]
Nice, I really like the world model! 

I've some progress on this as well, got it working (with a lot of bugs) on WebRTC+WebSockets now I think –
1. From the [server repo](https://github.com/donmccurdy/proxy-controls-server), run `npm run dev-server` and `npm run dev-client` in two terminals, and open [localhost:3000](http://localhost:3000) in a browser.
2. From the [client repo](https://github.com/donmccurdy/aframe-proxy-controls), run `npm run dev`, and open [localhost:8000](http://localhost:8000).

With the first page open and in focus, you can type or use the gamepad and its events will be sent to the remote page. The keyboard events don't do anything yet, but a gamepad should actually let you move around.

The pairing process is really rough right now (takes 3 terminals, and I have to refresh pages and restart the server a lot to get things connected) but hopefully that can be cleaned up more. I'll try to get the server part running as a service so that anybody can use it.

_Lots_ still to do on this, so I'm going to start tracking progress with an issue ([v0.5.0 Tasks](https://github.com/donmccurdy/proxy-controls-server/issues/2)) on the other repo.

**Comment by Feijk** [comment]
Looking good! I tested the current implementation of yours and the main idea seems to be working, but connections are really unreliable at the moment. For some reason even if room connections succeed the view needs multiple refreshes to establish a connection for keyboard events to be transferred. I'm currently at work and don't have a gamepad to test with, but will continue once I get home.

I'll try debug the connection issues and figure out what's wrong. Should we continue this conversation in [v0.5.0](https://github.com/donmccurdy/proxy-controls-server/issues/2) ?

I also updated the world model for testing to include some baked textures for testing. Get it [here](https://storage.googleapis.com/nvf-misc/collada_test_world.zip)

**Comment by donmccurdy** [comment]
Sounds like the same issue I'm seeing yes, I haven't figured out what's going on yet really. Let's move discussion to that repo – I've just opened a second issue for the [unreliable connection problem](https://github.com/donmccurdy/proxy-controls-server/issues/3).

**Comment by donmccurdy** [comment]
Got something together that seems more stable now: https://proxy-controls.donmccurdy.com .. works with `gamepad-controls` so please feel free to try it out!

I haven't been seeing the connection issues as much either, but I'm still not sure what they were.. possibly related to Budo, I think.
